-- Liuyao Divination Supabase/Postgres schema.
-- Run this in the Supabase SQL editor or with `supabase db push`.

create extension if not exists pgcrypto;

create table if not exists public.divination_records (
  id varchar(50) primary key,
  timestamp bigint not null,
  question text not null,
  gender varchar(10),
  bazi text,
  method varchar(20) not null,
  ben_gua text not null,
  bian_gua text,
  decoration text not null,
  ai_analysis text,
  user_id varchar(50),
  is_verified boolean default false,
  actual_result text,
  verify_time bigint,
  accuracy_rating integer,
  user_notes text,
  created_at timestamptz default now()
);

create table if not exists public.trigrams (
  id integer generated by default as identity primary key,
  name varchar(50) not null unique,
  symbol varchar(50) not null,
  nature varchar(50) not null,
  element varchar(50) not null,
  number integer not null unique
);

create table if not exists public.gua_data (
  number integer primary key,
  name varchar(20) not null unique,
  upper_trigram varchar(10) not null,
  lower_trigram varchar(10) not null,
  gua_ci text,
  yao_ci text
);

create table if not exists public.users (
  id varchar(50) primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  email varchar(100) unique,
  real_name varchar(100),
  avatar varchar(255),
  status smallint not null default 1,
  deepseek_api_key varchar(255),
  api_key_updated_at timestamptz,
  login_fail_count integer default 0,
  locked_until timestamptz,
  last_password_change timestamptz,
  password_reset_token varchar(255),
  password_reset_expires timestamptz,
  email_verified boolean default false,
  email_verification_token varchar(255),
  two_factor_secret varchar(255),
  two_factor_enabled boolean default false,
  last_login_at timestamptz,
  last_login_ip varchar(45),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.roles (
  id varchar(50) primary key,
  role_name varchar(50) not null unique,
  role_code varchar(50) not null unique,
  description text,
  status smallint not null default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.permissions (
  id varchar(50) primary key,
  permission_name varchar(100) not null,
  permission_code varchar(100) not null unique,
  description text,
  module varchar(50),
  status smallint not null default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_roles (
  id varchar(50) primary key,
  user_id varchar(50) not null references public.users(id) on delete cascade,
  role_id varchar(50) not null references public.roles(id) on delete cascade,
  created_at timestamptz default now(),
  unique (user_id, role_id)
);

create table if not exists public.role_permissions (
  id varchar(50) primary key,
  role_id varchar(50) not null references public.roles(id) on delete cascade,
  permission_id varchar(50) not null references public.permissions(id) on delete cascade,
  created_at timestamptz default now(),
  unique (role_id, permission_id)
);

create table if not exists public.login_logs (
  id varchar(50) primary key,
  user_id varchar(50) references public.users(id) on delete set null,
  username varchar(50),
  ip_address varchar(45),
  user_agent text,
  login_status smallint not null,
  failure_reason text,
  session_id varchar(50),
  login_time timestamptz default now()
);

create table if not exists public.operation_logs (
  id varchar(50) primary key,
  user_id varchar(50) references public.users(id) on delete set null,
  username varchar(50),
  operation_type varchar(50),
  operation_module varchar(50),
  operation_description text,
  request_method varchar(20),
  request_url text,
  request_params text,
  response_status integer,
  ip_address varchar(45),
  user_agent text,
  execution_time integer,
  operation_time timestamptz default now()
);

create table if not exists public.user_sessions (
  id varchar(50) primary key,
  user_id varchar(50) not null references public.users(id) on delete cascade,
  session_token varchar(255) not null,
  device_info text,
  ip_address varchar(45),
  user_agent text,
  last_activity timestamptz default now(),
  expires_at timestamptz,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.invite_codes (
  id varchar(50) primary key,
  code varchar(50) not null unique,
  name varchar(100),
  description text,
  max_uses integer default 1,
  used_count integer default 0,
  expires_at timestamptz,
  status smallint not null default 1,
  created_by varchar(50) references public.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id varchar(50) primary key,
  user_id varchar(50) references public.users(id) on delete set null,
  username varchar(50),
  action varchar(100) not null,
  resource_type varchar(50),
  resource_id varchar(50),
  details text,
  ip_address varchar(45),
  user_agent text,
  status smallint not null,
  error_message text,
  created_at timestamptz default now()
);

create table if not exists public.token_blacklist (
  id varchar(50) primary key,
  token_jti varchar(255) not null unique,
  user_id varchar(50) references public.users(id) on delete cascade,
  token_type varchar(20) not null,
  created_at timestamptz default now(),
  expires_at timestamptz,
  reason varchar(255)
);

create table if not exists public.bazi_records (
  id varchar(50) primary key,
  user_id varchar(50) not null references public.users(id) on delete cascade,
  timestamp bigint not null,
  name varchar(100),
  gender varchar(10) not null,
  birth_datetime bigint not null,
  birth_location varchar(200),
  use_true_solar_time boolean default false,
  year_pillar varchar(10) not null,
  month_pillar varchar(10) not null,
  day_pillar varchar(10) not null,
  hour_pillar varchar(10) not null,
  bazi_data text not null,
  dayun_data text,
  qiyun_age integer,
  shun_pai boolean,
  ai_analysis text,
  ai_model varchar(50),
  ai_analyzed_at bigint,
  is_verified boolean default false,
  actual_feedback text,
  verify_time bigint,
  accuracy_rating integer,
  user_notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.jie_qi_data (
  id integer generated by default as identity primary key,
  year integer not null,
  jieqi_name varchar(20) not null,
  jieqi_datetime bigint not null,
  jieqi_type varchar(10),
  solar_term_index integer,
  unique (year, jieqi_name)
);

create table if not exists public.liu_shi_jia_zi (
  id integer generated by default as identity primary key,
  index_num integer not null unique,
  gan_zhi varchar(10) not null unique,
  gan varchar(10) not null,
  zhi varchar(10) not null,
  gan_wu_xing varchar(10),
  zhi_wu_xing varchar(10),
  na_yin varchar(20)
);

create table if not exists public.email_verifications (
  id varchar(50) primary key,
  user_id varchar(50) references public.users(id) on delete cascade,
  email varchar(100),
  token varchar(255) not null,
  verification_type varchar(50) not null,
  is_used boolean default false,
  used_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz default now()
);

create index if not exists idx_divination_records_user_id on public.divination_records(user_id);
create index if not exists idx_divination_records_created_at on public.divination_records(created_at);
create index if not exists idx_divination_records_timestamp on public.divination_records(timestamp);
create index if not exists idx_gua_data_trigrams on public.gua_data(upper_trigram, lower_trigram);
create index if not exists idx_users_status on public.users(status);
create index if not exists idx_roles_status on public.roles(status);
create index if not exists idx_permissions_module on public.permissions(module);
create index if not exists idx_login_logs_login_time on public.login_logs(login_time);
create index if not exists idx_operation_logs_operation_time on public.operation_logs(operation_time);
create index if not exists idx_user_sessions_user_id on public.user_sessions(user_id);
create index if not exists idx_user_sessions_token on public.user_sessions(session_token);
create index if not exists idx_token_blacklist_expires_at on public.token_blacklist(expires_at);
create index if not exists idx_bazi_records_user_id on public.bazi_records(user_id);
create index if not exists idx_bazi_records_timestamp on public.bazi_records(timestamp);

insert into public.trigrams (name, symbol, nature, element, number) values
  ('乾', '☰', '天', '金', 1),
  ('坤', '☷', '地', '土', 2),
  ('震', '☳', '雷', '木', 3),
  ('巽', '☴', '风', '木', 4),
  ('坎', '☵', '水', '水', 5),
  ('离', '☲', '火', '火', 6),
  ('艮', '☶', '山', '土', 7),
  ('兑', '☱', '泽', '金', 8)
on conflict (name) do update set
  symbol = excluded.symbol,
  nature = excluded.nature,
  element = excluded.element,
  number = excluded.number;

insert into public.roles (id, role_name, role_code, description, status) values
  ('role-admin-001', '管理员', 'admin', '拥有系统所有权限', 1),
  ('role-user-001', '普通用户', 'user', '可以使用基础功能', 1),
  ('role-vip-001', 'VIP用户', 'vip', '可以使用全部占卜和AI分析功能', 1)
on conflict (id) do update set
  role_name = excluded.role_name,
  role_code = excluded.role_code,
  description = excluded.description,
  status = excluded.status,
  updated_at = now();

insert into public.permissions (id, permission_name, permission_code, description, module, status) values
  ('perm-div-001', '创建占卜', 'divination:create', '允许创建新的占卜记录', 'divination', 1),
  ('perm-div-002', '查看占卜', 'divination:view', '允许查看占卜记录', 'divination', 1),
  ('perm-div-003', '删除占卜', 'divination:delete', '允许删除占卜记录', 'divination', 1),
  ('perm-div-004', '查看所有占卜', 'divination:viewAll', '允许查看所有用户的占卜记录', 'divination', 1),
  ('perm-div-005', '使用AI分析', 'divination:aiAnalysis', '允许使用AI分析功能', 'divination', 1),
  ('perm-user-001', '创建用户', 'user:create', '允许创建用户', 'user', 1),
  ('perm-user-002', '查看用户', 'user:view', '允许查看用户信息', 'user', 1),
  ('perm-user-003', '编辑用户', 'user:edit', '允许编辑用户信息', 'user', 1),
  ('perm-user-004', '删除用户', 'user:delete', '允许删除用户', 'user', 1),
  ('perm-user-005', '启用禁用用户', 'user:status', '允许启用或禁用用户', 'user', 1),
  ('perm-role-001', '创建角色', 'role:create', '允许创建角色', 'role', 1),
  ('perm-role-002', '查看角色', 'role:view', '允许查看角色', 'role', 1),
  ('perm-role-003', '编辑角色', 'role:edit', '允许编辑角色', 'role', 1),
  ('perm-role-004', '删除角色', 'role:delete', '允许删除角色', 'role', 1),
  ('perm-role-005', '分配权限', 'role:assignPermission', '允许为角色分配权限', 'role', 1),
  ('perm-perm-001', '查看权限', 'permission:view', '允许查看权限', 'permission', 1),
  ('perm-log-001', '查看登录日志', 'log:viewLogin', '允许查看登录日志', 'log', 1),
  ('perm-log-002', '查看操作日志', 'log:viewOperation', '允许查看操作日志', 'log', 1),
  ('perm-log-003', '删除日志', 'log:delete', '允许删除日志', 'log', 1),
  ('perm-log-004', '导出日志', 'log:export', '允许导出日志', 'log', 1),
  ('perm-session-001', '查看会话', 'session:view', '允许查看会话', 'session', 1),
  ('perm-session-002', '管理会话', 'session:manage', '允许管理会话', 'session', 1),
  ('perm-invite-001', '查看邀请码', 'invite:view', '允许查看邀请码', 'invite', 1),
  ('perm-invite-002', '创建邀请码', 'invite:create', '允许创建邀请码', 'invite', 1),
  ('perm-invite-003', '编辑邀请码', 'invite:edit', '允许编辑邀请码', 'invite', 1),
  ('perm-invite-004', '删除邀请码', 'invite:delete', '允许删除邀请码', 'invite', 1),
  ('perm-audit-001', '查看审计日志', 'audit:view', '允许查看审计日志', 'audit', 1),
  ('perm-audit-002', '导出审计日志', 'audit:export', '允许导出审计日志', 'audit', 1),
  ('perm-security-001', '查看安全信息', 'security:view', '允许查看安全信息', 'security', 1),
  ('perm-security-002', '锁定解锁账号', 'security:lockUnlock', '允许锁定或解锁账号', 'security', 1),
  ('perm-bazi-001', '创建八字记录', 'bazi:create', '允许创建八字记录', 'bazi', 1),
  ('perm-bazi-002', '查看八字记录', 'bazi:view', '允许查看八字记录', 'bazi', 1),
  ('perm-bazi-003', '删除八字记录', 'bazi:delete', '允许删除八字记录', 'bazi', 1),
  ('perm-bazi-004', 'AI分析八字', 'bazi:aiAnalysis', '允许AI分析八字', 'bazi', 1),
  ('perm-bazi-005', '验证八字反馈', 'bazi:verify', '允许验证八字反馈', 'bazi', 1)
on conflict (id) do update set
  permission_name = excluded.permission_name,
  permission_code = excluded.permission_code,
  description = excluded.description,
  module = excluded.module,
  status = excluded.status,
  updated_at = now();

insert into public.users (id, username, password, email, real_name, status, last_password_change) values
  ('user-admin-001', 'admin', '$2a$10$bsLON33LP5qd.3soxumKfezEDQvsnJ20cNv6IPPF5DeXzMpzi42yO', 'admin@liuyao.com', '系统管理员', 1, now()),
  ('user-test-001', 'testuser', '$2a$10$RkPAzV3AaTDwcukAKRod.eTh76DpXzfKk9uuf7fjdWkNoSR.Yl.se', 'test@liuyao.com', '测试用户', 1, now())
on conflict (id) do update set
  username = excluded.username,
  password = excluded.password,
  email = excluded.email,
  real_name = excluded.real_name,
  status = excluded.status,
  updated_at = now();

insert into public.role_permissions (id, role_id, permission_id)
select 'rp-admin-' || left(md5(r.id || p.id), 25), r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'admin' and p.status = 1
on conflict (role_id, permission_id) do nothing;

insert into public.role_permissions (id, role_id, permission_id)
select 'rp-user-' || left(md5(r.id || p.id), 26), r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'user'
  and p.permission_code in (
    'divination:create',
    'divination:view',
    'divination:delete',
    'divination:aiAnalysis',
    'bazi:create',
    'bazi:view',
    'bazi:delete',
    'bazi:aiAnalysis',
    'bazi:verify'
  )
on conflict (role_id, permission_id) do nothing;

insert into public.user_roles (id, user_id, role_id)
select 'ur-admin-001', u.id, r.id
from public.users u cross join public.roles r
where u.username = 'admin' and r.role_code = 'admin'
on conflict (user_id, role_id) do nothing;

insert into public.user_roles (id, user_id, role_id)
select 'ur-test-001', u.id, r.id
from public.users u cross join public.roles r
where u.username = 'testuser' and r.role_code = 'user'
on conflict (user_id, role_id) do nothing;

insert into public.invite_codes (id, code, name, description, max_uses, status) values
  ('invite-default-001', '1663929970', '默认邀请码', '系统默认邀请码', 1000, 1),
  ('invite-admin-001', 'ADMININVITE2024', '管理员邀请码', '管理员专用邀请码', 50, 1)
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  max_uses = excluded.max_uses,
  status = excluded.status,
  updated_at = now();

grant usage on schema public to anon, authenticated;
grant select on public.trigrams, public.gua_data to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;

alter table public.divination_records enable row level security;
alter table public.trigrams enable row level security;
alter table public.gua_data enable row level security;
alter table public.users enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;
alter table public.login_logs enable row level security;
alter table public.operation_logs enable row level security;
alter table public.user_sessions enable row level security;
alter table public.invite_codes enable row level security;
alter table public.audit_logs enable row level security;
alter table public.token_blacklist enable row level security;
alter table public.bazi_records enable row level security;
alter table public.jie_qi_data enable row level security;
alter table public.liu_shi_jia_zi enable row level security;
alter table public.email_verifications enable row level security;

drop policy if exists "lookup trigram read" on public.trigrams;
drop policy if exists "lookup gua read" on public.gua_data;
drop policy if exists "own divination read" on public.divination_records;
drop policy if exists "own divination insert" on public.divination_records;
drop policy if exists "own divination update" on public.divination_records;
drop policy if exists "own divination delete" on public.divination_records;
drop policy if exists "own bazi read" on public.bazi_records;
drop policy if exists "own bazi insert" on public.bazi_records;
drop policy if exists "own bazi update" on public.bazi_records;
drop policy if exists "own bazi delete" on public.bazi_records;

create policy "lookup trigram read" on public.trigrams for select to anon, authenticated using (true);
create policy "lookup gua read" on public.gua_data for select to anon, authenticated using (true);

create policy "own divination read" on public.divination_records for select to authenticated
using ((select auth.uid())::text = user_id);
create policy "own divination insert" on public.divination_records for insert to authenticated
with check ((select auth.uid())::text = user_id);
create policy "own divination update" on public.divination_records for update to authenticated
using ((select auth.uid())::text = user_id)
with check ((select auth.uid())::text = user_id);
create policy "own divination delete" on public.divination_records for delete to authenticated
using ((select auth.uid())::text = user_id);

create policy "own bazi read" on public.bazi_records for select to authenticated
using ((select auth.uid())::text = user_id);
create policy "own bazi insert" on public.bazi_records for insert to authenticated
with check ((select auth.uid())::text = user_id);
create policy "own bazi update" on public.bazi_records for update to authenticated
using ((select auth.uid())::text = user_id)
with check ((select auth.uid())::text = user_id);
create policy "own bazi delete" on public.bazi_records for delete to authenticated
using ((select auth.uid())::text = user_id);
